### ISSUE TITLE
Implement ConnectionFactory Discovery

### ISSUE THREAD

**Issue by nebhale** [r2dbc/r2dbc-proxy#2]
Should this project implement `ConnectionFactory` discovery?

r2dbc/r2dbc-spi#10

**Comment by ttddyy** [comment]
I think yes and no.

By having proxy `ConnectionFactory` itself does not do anything. Once listeners are registered, then it has value to do it.

**1.  Allow registering listeners via URL query**

For example, this URL may automatically create a proxy for mysql `ConnectionFactory` and registers two listeners.

_r2dbc:proxy:mysql://localhost:3306/my_database?listener=com.example.MyListenerA,com.example.MyListenerB_

This is convenient but in a way limited because the instantiation of the listener can only be done with default constructor. (no dependency injection)

This also leaves a question of how we treat the query part for the pass-through URL.
If we want to specify some query parameter for mysql in this case, does it mix parameters for mysql and proxy? That may lead to naming collision.


**2. In spring-boot with auto-configuration**
Auto-configuration can play with proxy `ConnectionFactory` when it finds a proxy created by URL parsing. For example, automatically inject available listener beans or create new listeners and inject them.
On the other hand, auto-configuration can create a proxy without URL parsing. For example, when it finds listener beans in its application-context or it is enabled by property such as `spring.r2dbc.proxy=true`.
So, having `ConnectionFactory` discovery for proxy may not have much of benefit.


So, I think outside of spring environment, if we want to auto register listeners with default instantiation, we can implement `ConnectionFactory` discovery in proxy.
In that case, first we need to decide how to specify listeners in pass-through URL.

**Comment by ttddyy** [comment]
Implemented via https://github.com/r2dbc/r2dbc-proxy/pull/6
