### ISSUE TITLE
Ability to capture entirety of query execution, including Result processing

### ISSUE THREAD

**Issue by osi** [r2dbc/r2dbc-proxy#71]
As of `0.8.2`, one can get before/after callbacks for `Statement.execute`, `Result.getRowsUpdated` and `Result.map`. There's also a callback that fires for each item in `Result.map`

However, there's no direct way to capture the duration from the start of `Statement.execute` until the end of either `getRowsUpdated` or `map`.  One can keep state in the associated `ConnectionInfo`, but there's no guaranteed way of associating the result callbacks to the associated query (which is useful if one is generating trace data)

**Comment by ttddyy** [comment]
Hi @osi,

Thanks for the suggestion.
Currently there is no callback at the end of processing `Result`.

Since you mentioned `trace data`, is it distributed tracing?
If so, usually you can retrieve current span at any place from tracer. So that you can associate current query to the span when query is executed via `[before|after]Query` callback, then at connection close, which is slightly different from the end of `Result` processing but almost equivalent, you can annotate the span. Then, in tracing UI, it is visually available to get the duration from executing query till end of its result processing via annotation.

Please see this listener implementation for tracing with Sleuth.
https://github.com/ttddyy/r2dbc-proxy-examples/blob/master/listener-example/src/main/java/io/r2dbc/examples/TracingExecutionListener.java


Another approach is you can store values to `ConnectionInfo#getValueStore`.
During lifecycle of executing query and processing result, same connection should be used. This means whenever retrieving `ConnectionInfo`, it is always associated to the same `ConnectionInfo`/`Connection` instance.

You can put the start time at `Statement#execute` and retrieve it to calculate start-to-finish duration at `Connection#close`. 
Also, you can associate the query to the same `ConnectionInfo` from `afterQuery` callback method since this uses the same connection which resolves to the same `ConnectionInfo`.

Does this approach meet your need?

**Comment by osi** [comment]
Yes, this is distributed tracing. That example is what we started with, but then realized it wasn't capturing the full duration of the query, as some important processing is done as part of `Result#map` that we want to have included into the span for the query.

In the reactive world, I like to try to avoid depending on magic thread-locals to provide external state. I'm okay with dealing with this to get the tracer itself, but once a connection span has been created, it is otherwise possible to use the `ValueStore` to store information. 

What I'm doing at the moment is relying on the fact that we don't do any concurrent query execution, and temporarily storing the query span into `ConnectionInfo#getValueStore` for the brief duration between `afterQuery` and the `before_OnResult` callback. 

Given the other methods that help track query execution (such as `onEachQueryResult`), I felt that having a `ValueStore` that was able to store state across the entire lifecycle of query execution would be a nice addition to the API.

**Comment by ttddyy** [comment]
I checked the code and I think what you need is `ValueStore` associated to `QueryExecutionInfo`( `QueryExecutionInfo#getValueStore()`) 

Let's say executing a query which returns 3 rows with value 100, 200, 300.

The callback method order is:

- beforeQuery()
- eachQueryResult()  // 100
- eachQueryResult()  // 200
- eachQueryResult()  // 300
- afterQuery()

These callback methods receives `QueryExecutionInfo`.
So, they have access to the context of the executing query.

Also, `QueryExecutionInfo` has `ValueStore` associated. (`QueryExecutionInfo#getValueStore()`)
The value store is available during those callbacks under the scope of query execution.
You can put a query span and can retrieve it in `eachQueryResult`.

`QueryExecutionInfo#getExecuteDuration` is only available in `afterQuery()` which contains the duration from `beforeQuery` to `afterQuery` which includes result processing time.

**Comment by ttddyy** [comment]
`afterQuery` callback captures duration including processing each query result.
JavaDoc has updated to mention the callback order.
